name: React component library


on:
  push:
    branches:
      - "*"


env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  GIT_URL: github.com/RainThief/react-lint-config.git
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


jobs:
  check:
    name: Check and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Static analysis
        run: ./run_static_analysis.sh

      - name: Dependency audit
        run: ./run_audit.sh


  publish:
    name: Tag and publish
    if: github.ref == 'refs/heads/master' && github.event.pull_request.merged
    runs-on: ubuntu-20.04
    needs: [check]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Extract Branch Name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: echo branhc name
        run: echo $BRANCH

      - name: Tag release
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          yarn version --new-version patch
          git push "https://$GITHUB_TOKEN@$GIT_URL"
          git push "https://$GITHUB_TOKEN@$GIT_URL" --tags

      - name: Publish release
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          npm publish
